function fish_greeting
    echo '       .,,.                                                                   '
    echo '       ,KMKkkkkkkkklll. ..                             ..       .,,,.         '
    echo '    .lkKKl,,,,,,,lkkKMKkKkll. ..                 ..,l,lKKkkkkkkkKMMKl.        '
    echo '   .lKKl.           .,,lkkKMKkKk,. ,l.  ,l. ,l. .kKKKkkl,,,,,,,,,lkKMKkl.     '
    echo ' .,kMk.   .,,,,,.         .,,lkKMKkKMKkkKMklKMKkKKl,.       .,,,.  .,kMKl.    '
    echo ' .kMk.    .,lkKMKkkl.        ...,lKMMk,llkMMklKKl.  .... .lkKKl,.    .kMl     '
    echo ' .kMl         .,,lKMKkl.  .. lKl. .ll.   .ll. ..  ,lkKKklKMKl.        lmk.    '
    echo '.kMk.             .lKMMKllKKkKKKl                .kMKKMMMMMl..        lmk.    '
    echo ' ,KK,              .KMKKKKklkKl..                 ,l..,lKKKKKx,l,    ,KKl.    '
    echo '.lKK,          ..,,lMK,....  ..                         ..lKkKMMl .. lMKl.    '
    echo ' lMl         ..lKKKKMK,                                   .. lKKKlkl .kMk.    '
    echo '.kMl         lKKKKMk,.                                       ...lKMK, lMk.    '
    echo ' lMk.      ,lkMk.,l.                                             ,lkl,KK,     '
    echo ' ,KMl     .kkll,                     .,.                ..         ..,Kk,.    '
    echo ' .kMk.    lMl      .lkkkkkkkl,,.    ,KMl                lk,     .lkkkkKMMK,   '
    echo '  ,KMl    ,l.     .lklkMk,,,lKMKkl,lKMMl                lMKl,,lkkkl,,kMMMMk.  '
    echo '   lMK.               lMl    .,lkkKMKl,.                .lKMMKkl.   .kMKKMK,  '
    echo '   ,KMKl.             lMk.       .kMl                     ,KMk.  .,lKKl.,KMk. '
    echo ' .,lKKkl.             ,KMKl,,,,,lKKl.      .lkkkkkkkkkl.   ,KMKkkKKkl.  lMK,  '
    echo ' ,KMKk,.               .lkkkkkkkkl.        lMMMMMMMMMMMl    .,,,,,.     ,KMk. '
    echo ' .lKMMK,                                   .kMMMMMMMMMMl                 lMMl '
    echo '  .lkKMk..l,                .ll,.           .lKMMMMMMkl.       .,ll.     lMK. '
    echo ' .,,lKKl.lMKkl.            ,KK,               .,lKMKl.           ,KK,    lMK, '
    echo ' .lKMMk,..,,,,.            lMl                  .kMl              lMl   ,KMMK,'
    echo '   ,KMMK.   ,Kl            lMl          .,,,,,lkKMMKkl,,.         lMl   lMKkl.'
    echo '  .kMkl.   ,KK,            lMl          .kMMMMKKMMMMKKMMKl.      ,KMl   lMKl. '
    echo '  .lkKKkkl.lMKkkl.         ,KKl.         .lkKMkkMKKMkkMk,.     .lKMk.   .kMMl '
    echo '     .lKMMl.,,,,. ..        ,KMKkl.         .lKKl..lKKl.      .kKkl.   ,kKMK, '
    echo '      .kMMKk,    .kl.,,.     .,,lkl.   ..     ..    ..  ..   .ll.   .,,kMMk.  '
    echo '     .lKMMMKl,,,.lMKKKl.               lKl.           .lKl          lMKKMK,   '
    echo '    .kMMKkkkkkKMl.lkk,                 .kMKl,.     .,lKKl.       .lkKMl.,.    '
    echo '   .lKMMk.    lMKkKMMKk.,,              .lkKMKkkkkkKMKl.      ,k,lKKMK,       '
    echo '     ,KKl. .. .,,,,kMKl.lK, .,,.           .,,,,,,,,,.   ,;,lkKMKk,.,.        '
    echo '   .lKMk. .kl.l,   .,.  lMKkKKKklkk,.,,,,.             .,kMMKKMk,.            '
    echo '   .lKMK,.kMKkk,        ,kl,,.lMKlkKKKkKMK,.,,lllllkkkkkKKll,lMl              '
    echo '   .lKMk..,,,.                .,. lKl. .ll.lKKMKkl,lKKl...  .kMKl.            '
    echo '  .lKMk.                   ,l. .. ..       ...l,    ..     ,KMKl,.            '
    echo '  ,KMKl.  ..               lMklKl                          lMMk.              '
    echo ' .lKMkl.  lk.,l.  .lx,     ,kMKl.                                             '
    echo ' .lKk.    lMKKMl lKKl                                                         '
end
